medical_data_profile:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST') }}"
      user: "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      port: "{{ env_var('POSTGRES_PORT', 5432) }}"
      dbname: "{{ env_var('POSTGRES_DB') }}"
      schema: raw
      threads: 4
      keepalives_idle: 0
      connect_timeout: 10