medical_data_profile:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: postgres
      port: 5432
      dbname: medical_data
      schema: raw
      threads: 4
      keepalives_idle: 0
      connect_timeout: 10